/*
Alpaca Broker API

Open brokerage accounts, enable commission-free trading, and manage the ongoing user experience with Alpaca Broker API

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
	"fmt"
)

// JournalResource - struct for JournalResource
type JournalResource struct {
	JournalJNLC *JournalJNLC
	JournalJNLS *JournalJNLS
}

// JournalJNLCAsJournalResource is a convenience function that returns JournalJNLC wrapped in JournalResource
func JournalJNLCAsJournalResource(v *JournalJNLC) JournalResource {
	return JournalResource{ JournalJNLC: v}
}

// JournalJNLSAsJournalResource is a convenience function that returns JournalJNLS wrapped in JournalResource
func JournalJNLSAsJournalResource(v *JournalJNLS) JournalResource {
	return JournalResource{ JournalJNLS: v}
}


// Unmarshal JSON data into one of the pointers in the struct
func (dst *JournalResource) UnmarshalJSON(data []byte) error {
	var err error
	match := 0
	// try to unmarshal data into JournalJNLC
	err = json.Unmarshal(data, &dst.JournalJNLC)
	if err == nil {
		jsonJournalJNLC, _ := json.Marshal(dst.JournalJNLC)
		if string(jsonJournalJNLC) == "{}" { // empty struct
			dst.JournalJNLC = nil
		} else {
			match++
		}
	} else {
		dst.JournalJNLC = nil
	}

	// try to unmarshal data into JournalJNLS
	err = json.Unmarshal(data, &dst.JournalJNLS)
	if err == nil {
		jsonJournalJNLS, _ := json.Marshal(dst.JournalJNLS)
		if string(jsonJournalJNLS) == "{}" { // empty struct
			dst.JournalJNLS = nil
		} else {
			match++
		}
	} else {
		dst.JournalJNLS = nil
	}

	if match > 1 { // more than 1 match
		// reset to nil
		dst.JournalJNLC = nil
		dst.JournalJNLS = nil

		return fmt.Errorf("Data matches more than one schema in oneOf(JournalResource)")
	} else if match == 1 {
		return nil // exactly one match
	} else { // no match
		return fmt.Errorf("Data failed to match schemas in oneOf(JournalResource)")
	}
}

// Marshal data from the first non-nil pointers in the struct to JSON
func (src JournalResource) MarshalJSON() ([]byte, error) {
	if src.JournalJNLC != nil {
		return json.Marshal(&src.JournalJNLC)
	}

	if src.JournalJNLS != nil {
		return json.Marshal(&src.JournalJNLS)
	}

	return nil, nil // no data in oneOf schemas
}

// Get the actual instance
func (obj *JournalResource) GetActualInstance() (interface{}) {
	if obj.JournalJNLC != nil {
		return obj.JournalJNLC
	}

	if obj.JournalJNLS != nil {
		return obj.JournalJNLS
	}

	// all schemas are nil
	return nil
}

type NullableJournalResource struct {
	value *JournalResource
	isSet bool
}

func (v NullableJournalResource) Get() *JournalResource {
	return v.value
}

func (v *NullableJournalResource) Set(val *JournalResource) {
	v.value = val
	v.isSet = true
}

func (v NullableJournalResource) IsSet() bool {
	return v.isSet
}

func (v *NullableJournalResource) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableJournalResource(val *JournalResource) *NullableJournalResource {
	return &NullableJournalResource{value: val, isSet: true}
}

func (v NullableJournalResource) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableJournalResource) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


