/*
Alpaca Broker API

Open brokerage accounts, enable commission-free trading, and manage the ongoing user experience with Alpaca Broker API

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// CreateOrderRequestStopLoss struct for CreateOrderRequestStopLoss
type CreateOrderRequestStopLoss struct {
	StopPrice *float64 `json:"stop_price,omitempty"`
	LimitPrice *float64 `json:"limit_price,omitempty"`
}

// NewCreateOrderRequestStopLoss instantiates a new CreateOrderRequestStopLoss object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCreateOrderRequestStopLoss() *CreateOrderRequestStopLoss {
	this := CreateOrderRequestStopLoss{}
	return &this
}

// NewCreateOrderRequestStopLossWithDefaults instantiates a new CreateOrderRequestStopLoss object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCreateOrderRequestStopLossWithDefaults() *CreateOrderRequestStopLoss {
	this := CreateOrderRequestStopLoss{}
	return &this
}

// GetStopPrice returns the StopPrice field value if set, zero value otherwise.
func (o *CreateOrderRequestStopLoss) GetStopPrice() float64 {
	if o == nil || o.StopPrice == nil {
		var ret float64
		return ret
	}
	return *o.StopPrice
}

// GetStopPriceOk returns a tuple with the StopPrice field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreateOrderRequestStopLoss) GetStopPriceOk() (*float64, bool) {
	if o == nil || o.StopPrice == nil {
		return nil, false
	}
	return o.StopPrice, true
}

// HasStopPrice returns a boolean if a field has been set.
func (o *CreateOrderRequestStopLoss) HasStopPrice() bool {
	if o != nil && o.StopPrice != nil {
		return true
	}

	return false
}

// SetStopPrice gets a reference to the given float64 and assigns it to the StopPrice field.
func (o *CreateOrderRequestStopLoss) SetStopPrice(v float64) {
	o.StopPrice = &v
}

// GetLimitPrice returns the LimitPrice field value if set, zero value otherwise.
func (o *CreateOrderRequestStopLoss) GetLimitPrice() float64 {
	if o == nil || o.LimitPrice == nil {
		var ret float64
		return ret
	}
	return *o.LimitPrice
}

// GetLimitPriceOk returns a tuple with the LimitPrice field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreateOrderRequestStopLoss) GetLimitPriceOk() (*float64, bool) {
	if o == nil || o.LimitPrice == nil {
		return nil, false
	}
	return o.LimitPrice, true
}

// HasLimitPrice returns a boolean if a field has been set.
func (o *CreateOrderRequestStopLoss) HasLimitPrice() bool {
	if o != nil && o.LimitPrice != nil {
		return true
	}

	return false
}

// SetLimitPrice gets a reference to the given float64 and assigns it to the LimitPrice field.
func (o *CreateOrderRequestStopLoss) SetLimitPrice(v float64) {
	o.LimitPrice = &v
}

func (o CreateOrderRequestStopLoss) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if o.StopPrice != nil {
		toSerialize["stop_price"] = o.StopPrice
	}
	if o.LimitPrice != nil {
		toSerialize["limit_price"] = o.LimitPrice
	}
	return json.Marshal(toSerialize)
}

type NullableCreateOrderRequestStopLoss struct {
	value *CreateOrderRequestStopLoss
	isSet bool
}

func (v NullableCreateOrderRequestStopLoss) Get() *CreateOrderRequestStopLoss {
	return v.value
}

func (v *NullableCreateOrderRequestStopLoss) Set(val *CreateOrderRequestStopLoss) {
	v.value = val
	v.isSet = true
}

func (v NullableCreateOrderRequestStopLoss) IsSet() bool {
	return v.isSet
}

func (v *NullableCreateOrderRequestStopLoss) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCreateOrderRequestStopLoss(val *CreateOrderRequestStopLoss) *NullableCreateOrderRequestStopLoss {
	return &NullableCreateOrderRequestStopLoss{value: val, isSet: true}
}

func (v NullableCreateOrderRequestStopLoss) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCreateOrderRequestStopLoss) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


